# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/inthe/corotine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/inthe/corotine

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/inthe/corotine/CMakeFiles /home/inthe/corotine//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/inthe/corotine/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named sylar

# Build rule for target.
sylar: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sylar
.PHONY : sylar

# fast build rule for target.
sylar/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/build
.PHONY : sylar/fast

#=============================================================================
# Target rules for targets named test_http_connection

# Build rule for target.
test_http_connection: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_http_connection
.PHONY : test_http_connection

# fast build rule for target.
test_http_connection/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_http_connection.dir/build.make CMakeFiles/test_http_connection.dir/build
.PHONY : test_http_connection/fast

sylar/address.o: sylar/address.cpp.o
.PHONY : sylar/address.o

# target to build an object file
sylar/address.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/sylar/address.cpp.o
.PHONY : sylar/address.cpp.o

sylar/address.i: sylar/address.cpp.i
.PHONY : sylar/address.i

# target to preprocess a source file
sylar/address.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/sylar/address.cpp.i
.PHONY : sylar/address.cpp.i

sylar/address.s: sylar/address.cpp.s
.PHONY : sylar/address.s

# target to generate assembly for a file
sylar/address.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/sylar/address.cpp.s
.PHONY : sylar/address.cpp.s

sylar/bytearray.o: sylar/bytearray.cpp.o
.PHONY : sylar/bytearray.o

# target to build an object file
sylar/bytearray.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/sylar/bytearray.cpp.o
.PHONY : sylar/bytearray.cpp.o

sylar/bytearray.i: sylar/bytearray.cpp.i
.PHONY : sylar/bytearray.i

# target to preprocess a source file
sylar/bytearray.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/sylar/bytearray.cpp.i
.PHONY : sylar/bytearray.cpp.i

sylar/bytearray.s: sylar/bytearray.cpp.s
.PHONY : sylar/bytearray.s

# target to generate assembly for a file
sylar/bytearray.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/sylar/bytearray.cpp.s
.PHONY : sylar/bytearray.cpp.s

sylar/config.o: sylar/config.cpp.o
.PHONY : sylar/config.o

# target to build an object file
sylar/config.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/sylar/config.cpp.o
.PHONY : sylar/config.cpp.o

sylar/config.i: sylar/config.cpp.i
.PHONY : sylar/config.i

# target to preprocess a source file
sylar/config.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/sylar/config.cpp.i
.PHONY : sylar/config.cpp.i

sylar/config.s: sylar/config.cpp.s
.PHONY : sylar/config.s

# target to generate assembly for a file
sylar/config.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/sylar/config.cpp.s
.PHONY : sylar/config.cpp.s

sylar/env.o: sylar/env.cpp.o
.PHONY : sylar/env.o

# target to build an object file
sylar/env.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/sylar/env.cpp.o
.PHONY : sylar/env.cpp.o

sylar/env.i: sylar/env.cpp.i
.PHONY : sylar/env.i

# target to preprocess a source file
sylar/env.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/sylar/env.cpp.i
.PHONY : sylar/env.cpp.i

sylar/env.s: sylar/env.cpp.s
.PHONY : sylar/env.s

# target to generate assembly for a file
sylar/env.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/sylar/env.cpp.s
.PHONY : sylar/env.cpp.s

sylar/fd_manager.o: sylar/fd_manager.cpp.o
.PHONY : sylar/fd_manager.o

# target to build an object file
sylar/fd_manager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/sylar/fd_manager.cpp.o
.PHONY : sylar/fd_manager.cpp.o

sylar/fd_manager.i: sylar/fd_manager.cpp.i
.PHONY : sylar/fd_manager.i

# target to preprocess a source file
sylar/fd_manager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/sylar/fd_manager.cpp.i
.PHONY : sylar/fd_manager.cpp.i

sylar/fd_manager.s: sylar/fd_manager.cpp.s
.PHONY : sylar/fd_manager.s

# target to generate assembly for a file
sylar/fd_manager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/sylar/fd_manager.cpp.s
.PHONY : sylar/fd_manager.cpp.s

sylar/fiber.o: sylar/fiber.cpp.o
.PHONY : sylar/fiber.o

# target to build an object file
sylar/fiber.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/sylar/fiber.cpp.o
.PHONY : sylar/fiber.cpp.o

sylar/fiber.i: sylar/fiber.cpp.i
.PHONY : sylar/fiber.i

# target to preprocess a source file
sylar/fiber.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/sylar/fiber.cpp.i
.PHONY : sylar/fiber.cpp.i

sylar/fiber.s: sylar/fiber.cpp.s
.PHONY : sylar/fiber.s

# target to generate assembly for a file
sylar/fiber.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/sylar/fiber.cpp.s
.PHONY : sylar/fiber.cpp.s

sylar/hook.o: sylar/hook.cpp.o
.PHONY : sylar/hook.o

# target to build an object file
sylar/hook.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/sylar/hook.cpp.o
.PHONY : sylar/hook.cpp.o

sylar/hook.i: sylar/hook.cpp.i
.PHONY : sylar/hook.i

# target to preprocess a source file
sylar/hook.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/sylar/hook.cpp.i
.PHONY : sylar/hook.cpp.i

sylar/hook.s: sylar/hook.cpp.s
.PHONY : sylar/hook.s

# target to generate assembly for a file
sylar/hook.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/sylar/hook.cpp.s
.PHONY : sylar/hook.cpp.s

sylar/http/http.o: sylar/http/http.cpp.o
.PHONY : sylar/http/http.o

# target to build an object file
sylar/http/http.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/sylar/http/http.cpp.o
.PHONY : sylar/http/http.cpp.o

sylar/http/http.i: sylar/http/http.cpp.i
.PHONY : sylar/http/http.i

# target to preprocess a source file
sylar/http/http.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/sylar/http/http.cpp.i
.PHONY : sylar/http/http.cpp.i

sylar/http/http.s: sylar/http/http.cpp.s
.PHONY : sylar/http/http.s

# target to generate assembly for a file
sylar/http/http.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/sylar/http/http.cpp.s
.PHONY : sylar/http/http.cpp.s

sylar/http/http11_parser.rl.o: sylar/http/http11_parser.rl.cc.o
.PHONY : sylar/http/http11_parser.rl.o

# target to build an object file
sylar/http/http11_parser.rl.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/sylar/http/http11_parser.rl.cc.o
.PHONY : sylar/http/http11_parser.rl.cc.o

sylar/http/http11_parser.rl.i: sylar/http/http11_parser.rl.cc.i
.PHONY : sylar/http/http11_parser.rl.i

# target to preprocess a source file
sylar/http/http11_parser.rl.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/sylar/http/http11_parser.rl.cc.i
.PHONY : sylar/http/http11_parser.rl.cc.i

sylar/http/http11_parser.rl.s: sylar/http/http11_parser.rl.cc.s
.PHONY : sylar/http/http11_parser.rl.s

# target to generate assembly for a file
sylar/http/http11_parser.rl.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/sylar/http/http11_parser.rl.cc.s
.PHONY : sylar/http/http11_parser.rl.cc.s

sylar/http/http_connection.o: sylar/http/http_connection.cpp.o
.PHONY : sylar/http/http_connection.o

# target to build an object file
sylar/http/http_connection.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/sylar/http/http_connection.cpp.o
.PHONY : sylar/http/http_connection.cpp.o

sylar/http/http_connection.i: sylar/http/http_connection.cpp.i
.PHONY : sylar/http/http_connection.i

# target to preprocess a source file
sylar/http/http_connection.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/sylar/http/http_connection.cpp.i
.PHONY : sylar/http/http_connection.cpp.i

sylar/http/http_connection.s: sylar/http/http_connection.cpp.s
.PHONY : sylar/http/http_connection.s

# target to generate assembly for a file
sylar/http/http_connection.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/sylar/http/http_connection.cpp.s
.PHONY : sylar/http/http_connection.cpp.s

sylar/http/http_parser.o: sylar/http/http_parser.cpp.o
.PHONY : sylar/http/http_parser.o

# target to build an object file
sylar/http/http_parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/sylar/http/http_parser.cpp.o
.PHONY : sylar/http/http_parser.cpp.o

sylar/http/http_parser.i: sylar/http/http_parser.cpp.i
.PHONY : sylar/http/http_parser.i

# target to preprocess a source file
sylar/http/http_parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/sylar/http/http_parser.cpp.i
.PHONY : sylar/http/http_parser.cpp.i

sylar/http/http_parser.s: sylar/http/http_parser.cpp.s
.PHONY : sylar/http/http_parser.s

# target to generate assembly for a file
sylar/http/http_parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/sylar/http/http_parser.cpp.s
.PHONY : sylar/http/http_parser.cpp.s

sylar/http/http_server.o: sylar/http/http_server.cpp.o
.PHONY : sylar/http/http_server.o

# target to build an object file
sylar/http/http_server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/sylar/http/http_server.cpp.o
.PHONY : sylar/http/http_server.cpp.o

sylar/http/http_server.i: sylar/http/http_server.cpp.i
.PHONY : sylar/http/http_server.i

# target to preprocess a source file
sylar/http/http_server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/sylar/http/http_server.cpp.i
.PHONY : sylar/http/http_server.cpp.i

sylar/http/http_server.s: sylar/http/http_server.cpp.s
.PHONY : sylar/http/http_server.s

# target to generate assembly for a file
sylar/http/http_server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/sylar/http/http_server.cpp.s
.PHONY : sylar/http/http_server.cpp.s

sylar/http/http_session.o: sylar/http/http_session.cpp.o
.PHONY : sylar/http/http_session.o

# target to build an object file
sylar/http/http_session.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/sylar/http/http_session.cpp.o
.PHONY : sylar/http/http_session.cpp.o

sylar/http/http_session.i: sylar/http/http_session.cpp.i
.PHONY : sylar/http/http_session.i

# target to preprocess a source file
sylar/http/http_session.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/sylar/http/http_session.cpp.i
.PHONY : sylar/http/http_session.cpp.i

sylar/http/http_session.s: sylar/http/http_session.cpp.s
.PHONY : sylar/http/http_session.s

# target to generate assembly for a file
sylar/http/http_session.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/sylar/http/http_session.cpp.s
.PHONY : sylar/http/http_session.cpp.s

sylar/http/httpclient_parser.rl.o: sylar/http/httpclient_parser.rl.cc.o
.PHONY : sylar/http/httpclient_parser.rl.o

# target to build an object file
sylar/http/httpclient_parser.rl.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/sylar/http/httpclient_parser.rl.cc.o
.PHONY : sylar/http/httpclient_parser.rl.cc.o

sylar/http/httpclient_parser.rl.i: sylar/http/httpclient_parser.rl.cc.i
.PHONY : sylar/http/httpclient_parser.rl.i

# target to preprocess a source file
sylar/http/httpclient_parser.rl.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/sylar/http/httpclient_parser.rl.cc.i
.PHONY : sylar/http/httpclient_parser.rl.cc.i

sylar/http/httpclient_parser.rl.s: sylar/http/httpclient_parser.rl.cc.s
.PHONY : sylar/http/httpclient_parser.rl.s

# target to generate assembly for a file
sylar/http/httpclient_parser.rl.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/sylar/http/httpclient_parser.rl.cc.s
.PHONY : sylar/http/httpclient_parser.rl.cc.s

sylar/http/servlet.o: sylar/http/servlet.cpp.o
.PHONY : sylar/http/servlet.o

# target to build an object file
sylar/http/servlet.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/sylar/http/servlet.cpp.o
.PHONY : sylar/http/servlet.cpp.o

sylar/http/servlet.i: sylar/http/servlet.cpp.i
.PHONY : sylar/http/servlet.i

# target to preprocess a source file
sylar/http/servlet.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/sylar/http/servlet.cpp.i
.PHONY : sylar/http/servlet.cpp.i

sylar/http/servlet.s: sylar/http/servlet.cpp.s
.PHONY : sylar/http/servlet.s

# target to generate assembly for a file
sylar/http/servlet.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/sylar/http/servlet.cpp.s
.PHONY : sylar/http/servlet.cpp.s

sylar/iomanager.o: sylar/iomanager.cpp.o
.PHONY : sylar/iomanager.o

# target to build an object file
sylar/iomanager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/sylar/iomanager.cpp.o
.PHONY : sylar/iomanager.cpp.o

sylar/iomanager.i: sylar/iomanager.cpp.i
.PHONY : sylar/iomanager.i

# target to preprocess a source file
sylar/iomanager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/sylar/iomanager.cpp.i
.PHONY : sylar/iomanager.cpp.i

sylar/iomanager.s: sylar/iomanager.cpp.s
.PHONY : sylar/iomanager.s

# target to generate assembly for a file
sylar/iomanager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/sylar/iomanager.cpp.s
.PHONY : sylar/iomanager.cpp.s

sylar/mutex.o: sylar/mutex.cpp.o
.PHONY : sylar/mutex.o

# target to build an object file
sylar/mutex.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/sylar/mutex.cpp.o
.PHONY : sylar/mutex.cpp.o

sylar/mutex.i: sylar/mutex.cpp.i
.PHONY : sylar/mutex.i

# target to preprocess a source file
sylar/mutex.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/sylar/mutex.cpp.i
.PHONY : sylar/mutex.cpp.i

sylar/mutex.s: sylar/mutex.cpp.s
.PHONY : sylar/mutex.s

# target to generate assembly for a file
sylar/mutex.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/sylar/mutex.cpp.s
.PHONY : sylar/mutex.cpp.s

sylar/scheduler.o: sylar/scheduler.cpp.o
.PHONY : sylar/scheduler.o

# target to build an object file
sylar/scheduler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/sylar/scheduler.cpp.o
.PHONY : sylar/scheduler.cpp.o

sylar/scheduler.i: sylar/scheduler.cpp.i
.PHONY : sylar/scheduler.i

# target to preprocess a source file
sylar/scheduler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/sylar/scheduler.cpp.i
.PHONY : sylar/scheduler.cpp.i

sylar/scheduler.s: sylar/scheduler.cpp.s
.PHONY : sylar/scheduler.s

# target to generate assembly for a file
sylar/scheduler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/sylar/scheduler.cpp.s
.PHONY : sylar/scheduler.cpp.s

sylar/socket.o: sylar/socket.cpp.o
.PHONY : sylar/socket.o

# target to build an object file
sylar/socket.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/sylar/socket.cpp.o
.PHONY : sylar/socket.cpp.o

sylar/socket.i: sylar/socket.cpp.i
.PHONY : sylar/socket.i

# target to preprocess a source file
sylar/socket.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/sylar/socket.cpp.i
.PHONY : sylar/socket.cpp.i

sylar/socket.s: sylar/socket.cpp.s
.PHONY : sylar/socket.s

# target to generate assembly for a file
sylar/socket.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/sylar/socket.cpp.s
.PHONY : sylar/socket.cpp.s

sylar/socket_stream.o: sylar/socket_stream.cpp.o
.PHONY : sylar/socket_stream.o

# target to build an object file
sylar/socket_stream.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/sylar/socket_stream.cpp.o
.PHONY : sylar/socket_stream.cpp.o

sylar/socket_stream.i: sylar/socket_stream.cpp.i
.PHONY : sylar/socket_stream.i

# target to preprocess a source file
sylar/socket_stream.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/sylar/socket_stream.cpp.i
.PHONY : sylar/socket_stream.cpp.i

sylar/socket_stream.s: sylar/socket_stream.cpp.s
.PHONY : sylar/socket_stream.s

# target to generate assembly for a file
sylar/socket_stream.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/sylar/socket_stream.cpp.s
.PHONY : sylar/socket_stream.cpp.s

sylar/stream.o: sylar/stream.cpp.o
.PHONY : sylar/stream.o

# target to build an object file
sylar/stream.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/sylar/stream.cpp.o
.PHONY : sylar/stream.cpp.o

sylar/stream.i: sylar/stream.cpp.i
.PHONY : sylar/stream.i

# target to preprocess a source file
sylar/stream.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/sylar/stream.cpp.i
.PHONY : sylar/stream.cpp.i

sylar/stream.s: sylar/stream.cpp.s
.PHONY : sylar/stream.s

# target to generate assembly for a file
sylar/stream.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/sylar/stream.cpp.s
.PHONY : sylar/stream.cpp.s

sylar/tcp_server.o: sylar/tcp_server.cpp.o
.PHONY : sylar/tcp_server.o

# target to build an object file
sylar/tcp_server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/sylar/tcp_server.cpp.o
.PHONY : sylar/tcp_server.cpp.o

sylar/tcp_server.i: sylar/tcp_server.cpp.i
.PHONY : sylar/tcp_server.i

# target to preprocess a source file
sylar/tcp_server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/sylar/tcp_server.cpp.i
.PHONY : sylar/tcp_server.cpp.i

sylar/tcp_server.s: sylar/tcp_server.cpp.s
.PHONY : sylar/tcp_server.s

# target to generate assembly for a file
sylar/tcp_server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/sylar/tcp_server.cpp.s
.PHONY : sylar/tcp_server.cpp.s

sylar/thread.o: sylar/thread.cpp.o
.PHONY : sylar/thread.o

# target to build an object file
sylar/thread.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/sylar/thread.cpp.o
.PHONY : sylar/thread.cpp.o

sylar/thread.i: sylar/thread.cpp.i
.PHONY : sylar/thread.i

# target to preprocess a source file
sylar/thread.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/sylar/thread.cpp.i
.PHONY : sylar/thread.cpp.i

sylar/thread.s: sylar/thread.cpp.s
.PHONY : sylar/thread.s

# target to generate assembly for a file
sylar/thread.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/sylar/thread.cpp.s
.PHONY : sylar/thread.cpp.s

sylar/timer.o: sylar/timer.cpp.o
.PHONY : sylar/timer.o

# target to build an object file
sylar/timer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/sylar/timer.cpp.o
.PHONY : sylar/timer.cpp.o

sylar/timer.i: sylar/timer.cpp.i
.PHONY : sylar/timer.i

# target to preprocess a source file
sylar/timer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/sylar/timer.cpp.i
.PHONY : sylar/timer.cpp.i

sylar/timer.s: sylar/timer.cpp.s
.PHONY : sylar/timer.s

# target to generate assembly for a file
sylar/timer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/sylar/timer.cpp.s
.PHONY : sylar/timer.cpp.s

sylar/uri.rl.o: sylar/uri.rl.cc.o
.PHONY : sylar/uri.rl.o

# target to build an object file
sylar/uri.rl.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/sylar/uri.rl.cc.o
.PHONY : sylar/uri.rl.cc.o

sylar/uri.rl.i: sylar/uri.rl.cc.i
.PHONY : sylar/uri.rl.i

# target to preprocess a source file
sylar/uri.rl.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/sylar/uri.rl.cc.i
.PHONY : sylar/uri.rl.cc.i

sylar/uri.rl.s: sylar/uri.rl.cc.s
.PHONY : sylar/uri.rl.s

# target to generate assembly for a file
sylar/uri.rl.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/sylar/uri.rl.cc.s
.PHONY : sylar/uri.rl.cc.s

sylar/util.o: sylar/util.cpp.o
.PHONY : sylar/util.o

# target to build an object file
sylar/util.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/sylar/util.cpp.o
.PHONY : sylar/util.cpp.o

sylar/util.i: sylar/util.cpp.i
.PHONY : sylar/util.i

# target to preprocess a source file
sylar/util.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/sylar/util.cpp.i
.PHONY : sylar/util.cpp.i

sylar/util.s: sylar/util.cpp.s
.PHONY : sylar/util.s

# target to generate assembly for a file
sylar/util.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/sylar/util.cpp.s
.PHONY : sylar/util.cpp.s

tests/test_http_connection.o: tests/test_http_connection.cpp.o
.PHONY : tests/test_http_connection.o

# target to build an object file
tests/test_http_connection.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_http_connection.dir/build.make CMakeFiles/test_http_connection.dir/tests/test_http_connection.cpp.o
.PHONY : tests/test_http_connection.cpp.o

tests/test_http_connection.i: tests/test_http_connection.cpp.i
.PHONY : tests/test_http_connection.i

# target to preprocess a source file
tests/test_http_connection.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_http_connection.dir/build.make CMakeFiles/test_http_connection.dir/tests/test_http_connection.cpp.i
.PHONY : tests/test_http_connection.cpp.i

tests/test_http_connection.s: tests/test_http_connection.cpp.s
.PHONY : tests/test_http_connection.s

# target to generate assembly for a file
tests/test_http_connection.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_http_connection.dir/build.make CMakeFiles/test_http_connection.dir/tests/test_http_connection.cpp.s
.PHONY : tests/test_http_connection.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... sylar"
	@echo "... test_http_connection"
	@echo "... sylar/address.o"
	@echo "... sylar/address.i"
	@echo "... sylar/address.s"
	@echo "... sylar/bytearray.o"
	@echo "... sylar/bytearray.i"
	@echo "... sylar/bytearray.s"
	@echo "... sylar/config.o"
	@echo "... sylar/config.i"
	@echo "... sylar/config.s"
	@echo "... sylar/env.o"
	@echo "... sylar/env.i"
	@echo "... sylar/env.s"
	@echo "... sylar/fd_manager.o"
	@echo "... sylar/fd_manager.i"
	@echo "... sylar/fd_manager.s"
	@echo "... sylar/fiber.o"
	@echo "... sylar/fiber.i"
	@echo "... sylar/fiber.s"
	@echo "... sylar/hook.o"
	@echo "... sylar/hook.i"
	@echo "... sylar/hook.s"
	@echo "... sylar/http/http.o"
	@echo "... sylar/http/http.i"
	@echo "... sylar/http/http.s"
	@echo "... sylar/http/http11_parser.rl.o"
	@echo "... sylar/http/http11_parser.rl.i"
	@echo "... sylar/http/http11_parser.rl.s"
	@echo "... sylar/http/http_connection.o"
	@echo "... sylar/http/http_connection.i"
	@echo "... sylar/http/http_connection.s"
	@echo "... sylar/http/http_parser.o"
	@echo "... sylar/http/http_parser.i"
	@echo "... sylar/http/http_parser.s"
	@echo "... sylar/http/http_server.o"
	@echo "... sylar/http/http_server.i"
	@echo "... sylar/http/http_server.s"
	@echo "... sylar/http/http_session.o"
	@echo "... sylar/http/http_session.i"
	@echo "... sylar/http/http_session.s"
	@echo "... sylar/http/httpclient_parser.rl.o"
	@echo "... sylar/http/httpclient_parser.rl.i"
	@echo "... sylar/http/httpclient_parser.rl.s"
	@echo "... sylar/http/servlet.o"
	@echo "... sylar/http/servlet.i"
	@echo "... sylar/http/servlet.s"
	@echo "... sylar/iomanager.o"
	@echo "... sylar/iomanager.i"
	@echo "... sylar/iomanager.s"
	@echo "... sylar/mutex.o"
	@echo "... sylar/mutex.i"
	@echo "... sylar/mutex.s"
	@echo "... sylar/scheduler.o"
	@echo "... sylar/scheduler.i"
	@echo "... sylar/scheduler.s"
	@echo "... sylar/socket.o"
	@echo "... sylar/socket.i"
	@echo "... sylar/socket.s"
	@echo "... sylar/socket_stream.o"
	@echo "... sylar/socket_stream.i"
	@echo "... sylar/socket_stream.s"
	@echo "... sylar/stream.o"
	@echo "... sylar/stream.i"
	@echo "... sylar/stream.s"
	@echo "... sylar/tcp_server.o"
	@echo "... sylar/tcp_server.i"
	@echo "... sylar/tcp_server.s"
	@echo "... sylar/thread.o"
	@echo "... sylar/thread.i"
	@echo "... sylar/thread.s"
	@echo "... sylar/timer.o"
	@echo "... sylar/timer.i"
	@echo "... sylar/timer.s"
	@echo "... sylar/uri.rl.o"
	@echo "... sylar/uri.rl.i"
	@echo "... sylar/uri.rl.s"
	@echo "... sylar/util.o"
	@echo "... sylar/util.i"
	@echo "... sylar/util.s"
	@echo "... tests/test_http_connection.o"
	@echo "... tests/test_http_connection.i"
	@echo "... tests/test_http_connection.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

